# https://www.supplychaindataanalytics.com/hatching-objects-on-autocad-template-using-pywin32-python/
# Hatching objects in AutoCAD with pywin32

# Setting up environment using pywin32 module

import pythoncom
import win32gui
import win32com.client
import time
from math import pi
#from pyautocad import Autocad, APoint, aDouble

def connect_autocad():
    try:
        # ì‹¤í–‰ ì¤‘ì¸ AutoCAD ì¸ìŠ¤í„´ìŠ¤ì— ì—°ê²°
        acad_app = win32com.client.GetActiveObject("AutoCAD.Application")        
        #print("âœ… AutoCAD ì‹¤í–‰ ì¤‘ì…ë‹ˆë‹¤.")
        #Autocad(create_if_not_exists=False)                  # pyautocad ì—°ê²°
        #return Autocad(create_if_not_exists=False)          # pyautocad ì—°ê²°
        return acad_app                                      # pywin32 ì—°ê²°
    except Exception:
        #print("âŒ ì‹¤í–‰ ì¤‘ì¸ AutoCAD ì—†ìŒ. ìƒˆ ì¸ìŠ¤í„´ìŠ¤ë¥¼ ì‹œì‘í•©ë‹ˆë‹¤.")
        try:
            acad_app = win32com.client.Dispatch("AutoCAD.Application")
            #acad_app.Visible = True
            time.sleep(3)  # ë¡œë”© ëŒ€ê¸°
            #print("âœ… ìƒˆ AutoCAD ì¸ìŠ¤í„´ìŠ¤ ì‹œì‘ ì™„ë£Œ.")
            #Autocad(create_if_not_exists=False)              # pyautocad ì—°ê²°
            #return Autocad(create_if_not_exists=False)      # pyautocad ì—°ê²°
            return acad_app                                  # pywin32 ì—°ê²°
        except Exception as e:
            print("ğŸš« AutoCAD ì—°ê²° ì‹¤íŒ¨:", e)
            return None
    finally:
        hwnd = win32gui.FindWindow(None, acad_app.Caption)
        bring_autocad_to_front(hwnd)      

def bring_autocad_to_front(hwnd):
    try:
        #acad = win32com.client.GetActiveObject("AutoCAD.Application")
        #hwnd = win32gui.FindWindow(None, acad.Caption)
        if hwnd:
            win32gui.ShowWindow(hwnd, 5)  # SW_SHOW
            win32gui.SetForegroundWindow(hwnd)
            #print("âœ… AutoCAD ì°½ì„ ì „ë©´ìœ¼ë¡œ ì „í™˜ ì™„ë£Œ.")
        else:
            print("âŒ AutoCAD ì°½ì„ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤.")
    except Exception as e:
        print("ğŸš« ì˜¤ë¥˜:", e)

def draw_and_zoom(acad):
    if acad is None:
        print("AutoCAD ì—°ê²°ì´ ì•ˆ ë˜ì–´ ì¢…ë£Œí•©ë‹ˆë‹¤.")
        return
    else:
        # í˜„ì¬ ë„ë©´ê³¼ ëª¨ë¸ ê³µê°„ ê°ì²´ ì ‘ê·¼ ActiveDocument : win32com
        doc = acad.ActiveDocument
        acad_model = doc.ModelSpace
        acad_app = acad.Application

    # Creating loop of objects in AutoCAD
    #out_loop = []
    #sq = acad_model.AddPolyline(aDouble(0,0,0,1000,0,0,1000,1000,0,0,1000,0))            
    #sq = acad_model.AddPolyline(win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, [0,0,0,1000,0,0,1000,1000,0,0,1000,0]))    
    sq_Plist = aDouble(0,0,0,1000,0,0,1000,1000,0,0,1000,0)
    sq = acad_model.AddPolyline(sq_Plist)    
    #arc = acad_model.AddArc(APoint(0, 500, 0), 500, 90*pi/180, 270*pi/180)
    #arc = acad_model.AddArc(win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, [0, 500, 0]), 500, 90*pi/180, 270*pi/180)
    arc_plist = aDouble(0, 500, 0)
    arc = acad_model.AddArc(arc_plist, 500, 90*pi/180, 270*pi/180)

    # í™”ë©´ ê°±ì‹ 
    acad_app.Update()
    acad_app.ZoomExtents()

    #out_loop.append(sq)
    #out_loop.append(arc)

    #outer = variants(out_loop)
    #outer = win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH, [out_loop])
    #outer = variants(pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH, out_loop)
    outer = win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH, [sq, arc])

    # Creating hatch object and appending the hatch
    # object.AddHatch(PatternType, PatternName, Associativity)
    hatch = acad_model.AddHatch(0, "ANSI37", True)    

    #Now to add this hatch to the loop we have created, we will use the AppendOuterLoop method.
    hatch.AppendOuterLoop(outer)

    print(hatch.HatchStyle)
    print(hatch.PatternName)
    print(hatch.AssociativeHatch)

    print(round(hatch.Area,2))
    print(hatch.PatternAngle)
    print(hatch.PatternDouble)
    print(hatch.PatternScale)
    print(hatch.PatternSpace)
    print(hatch.PatternType)
    print(hatch.NumberOfLoops)

    # Now, letâ€™s change the pattern scale to 10.
    hatch.PatternScale = 10

    # í™”ë©´ ê°±ì‹ 
    acad_app.Update()
    acad_app.ZoomExtents()

    # Adding inner loop to hatched AutoCAD object loop
    #in_loop = []
    #in_loop.append(acad_model.AddCircle(APoint(250, 250, 0), 100))    
    #inner = variants(in_loop)
    
    #circle = acad_model.AddCircle(win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, [250, 250, 0]), 100)
    circle_Plist = aDouble(250, 250, 0)
    circle = acad_model.AddCircle(circle_Plist, 100)
    inner = win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH, [circle])

    hatch.AppendInnerLoop(inner)

    print(round(hatch.Area,2))

    # í™”ë©´ ê°±ì‹ 
    acad_app.Update()
    acad_app.ZoomExtents()

# Creating necessary constructors using pywin32 & pythoncom
def aDouble(*argv):
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, (argv))

def variants(object):
#def variants(typeVar, object):    
    #return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH, (object))    
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH, [object])
    #return win32com.client.VARIANT(typeVar, [object])


if __name__ == "__main__":    
    pythoncom.CoInitialize()  # COM ì´ˆê¸°í™”
    acad = connect_autocad() 
    draw_and_zoom(acad)
    pythoncom.CoUninitialize()
