# https://www.supplychaindataanalytics.com/rectangular-arrays-in-autocad-using-pyautocad-python/
# Rectangular AutoCAD arrays in pyautocad

import pythoncom
import win32gui
import win32com.client
import time
#from pyautocad import Autocad, APoint, aDouble

def connect_autocad():
    try:
        # ì‹¤í–‰ ì¤‘ì¸ AutoCAD ì¸ìŠ¤í„´ìŠ¤ì— ì—°ê²°
        acad_app = win32com.client.GetActiveObject("AutoCAD.Application")        
        #print("âœ… AutoCAD ì‹¤í–‰ ì¤‘ì…ë‹ˆë‹¤.")
        #Autocad(create_if_not_exists=False)                  # pyautocad ì—°ê²°
        #return Autocad(create_if_not_exists=False)          # pyautocad ì—°ê²°
        return acad_app                                      # pywin32 ì—°ê²°
    except Exception:
        #print("âŒ ì‹¤í–‰ ì¤‘ì¸ AutoCAD ì—†ìŒ. ìƒˆ ì¸ìŠ¤í„´ìŠ¤ë¥¼ ì‹œì‘í•©ë‹ˆë‹¤.")
        try:
            acad_app = win32com.client.Dispatch("AutoCAD.Application")
            #acad_app.Visible = True
            time.sleep(3)  # ë¡œë”© ëŒ€ê¸°
            #print("âœ… ìƒˆ AutoCAD ì¸ìŠ¤í„´ìŠ¤ ì‹œì‘ ì™„ë£Œ.")
            #Autocad(create_if_not_exists=False)              # pyautocad ì—°ê²°
            #return Autocad(create_if_not_exists=False)      # pyautocad ì—°ê²°
            return acad_app                                  # pywin32 ì—°ê²°
        except Exception as e:
            print("ğŸš« AutoCAD ì—°ê²° ì‹¤íŒ¨:", e)
            return None
    finally:
        hwnd = win32gui.FindWindow(None, acad_app.Caption)
        bring_autocad_to_front(hwnd)   

def bring_autocad_to_front(hwnd):
    try:
        #acad = win32com.client.GetActiveObject("AutoCAD.Application")
        #hwnd = win32gui.FindWindow(None, acad.Caption)
        if hwnd:
            win32gui.ShowWindow(hwnd, 5)  # SW_SHOW
            win32gui.SetForegroundWindow(hwnd)
            #print("âœ… AutoCAD ì°½ì„ ì „ë©´ìœ¼ë¡œ ì „í™˜ ì™„ë£Œ.")
        else:
            print("âŒ AutoCAD ì°½ì„ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤.")
    except Exception as e:
        print("ğŸš« ì˜¤ë¥˜:", e)
        

# Creating necessary constructors using pywin32 & pythoncom
def aDouble(*argv):
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, (argv))

def variants(object):
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH, [object])

# Creating array using boundaries as base
# Now, we will write a simple code to use the boundaries of objects as a base for creating array offsets for the rectangle.
# ì´ì œ ì‚¬ê°í˜•ì˜ ë°°ì—´ ì˜¤í”„ì…‹ì„ ìƒì„±í•˜ê¸° ìœ„í•œ ê¸°ì¤€ìœ¼ë¡œ ê°ì²´ì˜ ê²½ê³„ë¥¼ ì‚¬ìš©í•˜ëŠ” ê°„ë‹¨í•œ ì½”ë“œë¥¼ ì‘ì„±í•´ë³´ê² ìŠµë‹ˆë‹¤.
def array_rectangle(acad_model, x, y, z, r, c, lr, dr, dc, dl):
    l=int(input("Enter length of rectangle:"))
    w=int(input("Enter width of rectangle:"))
    rect = aDouble(x, y, z, x, y+w, z, x+l, y+w, z, x+l, y, z, x, y, z)
    rec = acad_model.AddPolyline(rect)
    arr = rec.ArrayRectangular(r, c, lr, dr+w, dc+l, dl)
    time.sleep(0.5)

# Now, we will write a simple code to create an array of circles to consider the boundaries of the circle as a base.
def array_circle(acad_model, x, y, rad,  r, c, lr, dr, dc, dl):
    c1P = aDouble(x, y, 0)
    c1 = acad_model.AddCircle(c1P, rad)
    arr2 = c1.ArrayRectangular(r, c, lr, dr+rad*2, dc+rad*2, dl)    
    time.sleep(0.5)


def draw_and_zoom(acad):    
    if acad is None:
        print("AutoCAD ì—°ê²°ì´ ì•ˆ ë˜ì–´ ì¢…ë£Œí•©ë‹ˆë‹¤.")
        return
    else:
        # í˜„ì¬ ë„ë©´ê³¼ ëª¨ë¸ ê³µê°„ ê°ì²´ ì ‘ê·¼ ActiveDocument : win32com
        doc = acad.ActiveDocument
        acad_model = doc.ModelSpace
        acad_app = acad.Application
    
    # Creating an object
    #To create an array I will draw a rectangle using the AddPolyline method to use it as a base object.
    sqp = aDouble(50, 150, 0, 50, 550, 0, 850, 550, 0, 850, 150, 0, 50, 150, 0)
    sq1 = acad_model.AddPolyline(sqp)

    # Working with the ArrayRectangular method
    # Now I will create a rectangular array. But before creating the same I explain how pyautocad creates the rectangular array based on the parameters that we pass on to the respective method.
    # Let us check out the syntax of the ArrayRectangular method:
    # Syntax: object.ArrayRectangular(NumberOfRows, NumberOfColumns, NumberOfLevels, DistBetweenRows, DistBetweenColumns, DistBetweenLevels)

    # Levels are 3D parameters. We use that to create layers of array along z axis. We set NumberOfLevels parameter to 1 always as we need to create the array on x, y plane.
    # The object in the selection set is assumed to be in the lower left-hand corner, and the array is generated up and to the right when the object is created.
    # For instance, letâ€™s create an array from the rectangle we have already created.
    arr1 = sq1.ArrayRectangular(5, 5, 1, 100, 100, 0)

    time.sleep(0.5)

    # í™”ë©´ ê°±ì‹ 
    acad_app.Update()
    acad_app.ZoomExtents()

    """
    # Creating array using boundaries as base
    # Now, we will write a simple code to use the boundaries of objects as a base for creating array offsets for the rectangle.
    # ì´ì œ ì‚¬ê°í˜•ì˜ ë°°ì—´ ì˜¤í”„ì…‹ì„ ìƒì„±í•˜ê¸° ìœ„í•œ ê¸°ì¤€ìœ¼ë¡œ ê°ì²´ì˜ ê²½ê³„ë¥¼ ì‚¬ìš©í•˜ëŠ” ê°„ë‹¨í•œ ì½”ë“œë¥¼ ì‘ì„±í•´ë³´ê² ìŠµë‹ˆë‹¤.
    def array_rectangle(x, y, z, r, c, lr, dr, dc, dl):
        l=int(input("Enter length of rectangle:"))
        w=int(input("Enter width of rectangle:"))
        rect = aDouble(x, y, z, x, y+w, z, x+l, y+w, z, x+l, y, z, x, y, z)
        rec = acad_model.AddPolyline(rect)
        arr = rec.ArrayRectangular(r, c, lr, dr+w, dc+l, dl)
    
    # In this code, we have to pass x, y, z coordinates as the base point for creating the rectangle. After that we will add the same set of parameters as mentioned in the command syntax.
    # Now, let us see how the array gets created after passing parameters in this code.
    # ì´ ì½”ë“œì—ì„œëŠ” ì‚¬ê°í˜•ì„ ìƒì„±í•˜ê¸° ìœ„í•œ ê¸°ì¤€ì ìœ¼ë¡œ x, y, z ì¢Œí‘œë¥¼ ì „ë‹¬í•´ì•¼ í•©ë‹ˆë‹¤. ê·¸ í›„ ëª…ë ¹ êµ¬ë¬¸ì— ì–¸ê¸‰ëœ ê²ƒê³¼ ë™ì¼í•œ ë§¤ê°œë³€ìˆ˜ ì§‘í•©ì„ ì¶”ê°€í•©ë‹ˆë‹¤.
    # ì´ì œ ì´ ì½”ë“œì—ì„œ ë§¤ê°œë³€ìˆ˜ë¥¼ ì „ë‹¬í•œ í›„ ë°°ì—´ì´ ì–´ë–»ê²Œ ìƒì„±ë˜ëŠ”ì§€ ì‚´í´ë³´ê² ìŠµë‹ˆë‹¤.
    array_rectangle(50, 150, 0, 3, 3, 1, 150, 250, 0)
    """    
    array_rectangle(acad_model, 50, 150, 0, 3, 3, 1, 150, 250, 0)

    time.sleep(0.5)

    # í™”ë©´ ê°±ì‹ 
    acad_app.Update()
    acad_app.ZoomExtents()


    # Array of circle
    # Let us try drawing an array for a circle using the existing command.
    cp = aDouble(100, 100, 0)
    c = acad_model.AddCircle(cp, 100)
    arr2 = c.ArrayRectangular(3, 3, 1, 50, 50, 0)

    time.sleep(0.5)

    # í™”ë©´ ê°±ì‹ 
    acad_app.Update()
    acad_app.ZoomExtents()

    array_circle(acad_model, 100, 100, 100, 3, 3, 1, 50, 100, 0)

    time.sleep(0.5)

    # í™”ë©´ ê°±ì‹ 
    acad_app.Update()
    acad_app.ZoomExtents()



if __name__ == "__main__":    
    pythoncom.CoInitialize()  # COM ì´ˆê¸°í™”
    acad = connect_autocad()    
    draw_and_zoom(acad)
    pythoncom.CoUninitialize()
