# https://www.supplychaindataanalytics.com/selectionset-object-in-autocad-with-python/
# SelectionSet object in AutoCAD with Python

#Preparing the code for this AutoCAD example
#For this coding example I am using the pythoncom and win32com modules. These modules initiate my application and perform various different tasks.

import win32com.client
import pythoncom
import win32gui
import time
#from pyautocad import Autocad, APoint, aDouble

def APoint(x, y, z = 0):
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, (x, y, z))

def aDouble(*xyz):
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, (xyz))

def aVariant(vObject):
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH, (vObject))

def connect_autocad():
    acad_app = None
    try:
        # ì‹¤í–‰ ì¤‘ì¸ AutoCAD ì¸ìŠ¤í„´ìŠ¤ì— ì—°ê²°
        acad_app = win32com.client.GetActiveObject("AutoCAD.Application")        
        #print("âœ… AutoCAD ì‹¤í–‰ ì¤‘ì…ë‹ˆë‹¤.")
        #Autocad(create_if_not_exists=False)                  # pyautocad ì—°ê²°
        #return Autocad(create_if_not_exists=False)          # pyautocad ì—°ê²°
        return acad_app                                      # pywin32 ì—°ê²°
    except Exception:
        #print("âŒ ì‹¤í–‰ ì¤‘ì¸ AutoCAD ì—†ìŒ. ìƒˆ ì¸ìŠ¤í„´ìŠ¤ë¥¼ ì‹œì‘í•©ë‹ˆë‹¤.")
        try:
            acad_app = win32com.client.Dispatch("AutoCAD.Application")
            #acad_app.Visible = True
            time.sleep(3)  # ë¡œë”© ëŒ€ê¸°
            #print("âœ… ìƒˆ AutoCAD ì¸ìŠ¤í„´ìŠ¤ ì‹œì‘ ì™„ë£Œ.")
            #Autocad(create_if_not_exists=False)              # pyautocad ì—°ê²°
            #return Autocad(create_if_not_exists=False)      # pyautocad ì—°ê²°
            return acad_app                                  # pywin32 ì—°ê²°
        except Exception as e:
            print("ğŸš« AutoCAD ì—°ê²° ì‹¤íŒ¨:", e)
            return None
    finally:
        if acad_app is not None:
            hwnd = win32gui.FindWindow(None, acad_app.Caption)
            bring_autocad_to_front(hwnd)   

def bring_autocad_to_front(hwnd):
    try:
        #acad = win32com.client.GetActiveObject("AutoCAD.Application")
        #hwnd = win32gui.FindWindow(None, acad.Caption)
        if hwnd:
            win32gui.ShowWindow(hwnd, 5)  # SW_SHOW
            win32gui.SetForegroundWindow(hwnd)
            #print("âœ… AutoCAD ì°½ì„ ì „ë©´ìœ¼ë¡œ ì „í™˜ ì™„ë£Œ.")
        else:
            print("âŒ AutoCAD ì°½ì„ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤.")
    except Exception as e:
        print("ğŸš« ì˜¤ë¥˜:", e)

def draw_and_zoom(acad):    
    if acad is None:
        print("AutoCAD ì—°ê²°ì´ ì•ˆ ë˜ì–´ ì¢…ë£Œí•©ë‹ˆë‹¤.")
        return
    else:
        # í˜„ì¬ ë„ë©´ê³¼ ëª¨ë¸ ê³µê°„ ê°ì²´ ì ‘ê·¼ ActiveDocument : win32com
        doc = acad.ActiveDocument
        acad_model = doc.ModelSpace
        acad_app = acad.Application

    # The SelectionSet AutoCAD object
    # First, let me explain the SelectionSet object in AutoCAD. A SelectionSet object simply refers to the set of items that I select in AutoCAD. While using AutoCAD I usually select items by creating a window around objects that I want to select from the drawing. In that case I usually do so by using the mouse. Different objects require SelectionSet as a reference object to perform different activities. Lets understand how to create SelectionSet object in Python.
    # Creating a SelectionSet AutoCAD object in Python
    # In this coding example, I will try to create two lines using the AddLine method. I add these two lines to a SelectionSet object.
    l1 = acad_model.AddLine(APoint(0, 0, 0),APoint(1000, 1000, 0))
    l2 = acad_model.AddLine(APoint(1000, 1000, 0),APoint(2000, 0, 0))
    # Now, I can create a SelectionSet object with the name â€œSS1â€ using the Add method. I use that method on the SelectionSets object. This SelectionSets object is a collection of all SelectionSet objects present inside the Document object.
    # To know more about the Document object and other AutoCAD objects, do check out my other Blog posts.    
    try:
        ss1 = doc.SelectionSets.Item("SS1")     # ê¸°ì¡´ì— ìˆìœ¼ë©´ ê°€ì ¸ì˜¤ê¸°
        ss1.Delete()                            # ì‚­ì œ
    except Exception:
        pass                                    # ì—†ìœ¼ë©´ ë¬´ì‹œ
    ss1 = doc.SelectionSets.Add("SS1")          # ìƒˆë¡œ ìƒì„±

    # The SelectionSet object takes an array of objects as input parameter. Those are the objects that are to be added to the SelectionSet. To do so, I use the AddItems method on the SelectionSet object to pass the created lines as input values. See below code.
    ss1.AddItems(aVariant([l1, l2]))
    # To confirm whether the SelectionSet is created and whether the two objects are present in the SelectionSet or not I can use two methods: Name and Count.
    print(ss1.Name)
    print(ss1.Count)

    # Methods of the SelectionSet AutoCAD object
    # There are also a few other methods that can be used to perform various different tasks on a SelectionSet object. For instance, Clear, Delete, Erase, Highlight, Item, RemoveItems, SelectOnScreen.
    # From the method mentioned above, the Item method can be used to fetch the Item present at a given index in a Collection, Group or SelectionSet.
    print(ss1.Item(0).ObjectName)

    # SelectionSet ë˜ëŠ” SelectionSetì˜ í•­ëª©ì„ ì‚­ì œí•˜ë ¤ë©´ Clear, Delete, Erase ë˜ëŠ” Remove Items ë©”ì„œë“œë¥¼ ì‚¬ìš©í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤. ì´ëŸ¬í•œ ë©”ì„œë“œì˜ ê¸°ëŠ¥ì€ ë‹¤ìŒê³¼ ê°™ìŠµë‹ˆë‹¤.
    # Clear:  ì´ ë©”ì„œë“œëŠ” SelectionSetì„ ë¹„ì›ë‹ˆë‹¤. SelectionSet ê°ì²´ëŠ” ì—¬ì „íˆ ì¡´ì¬í•˜ì§€ë§Œ í•­ëª©ì„ í¬í•¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤. ì´ì „ì— ì„ íƒ ì˜ì—­ì— ìˆë˜ í•­ëª©ì€ ì—¬ì „íˆ â€‹â€‹ì¡´ì¬í•˜ì§€ë§Œ ë” ì´ìƒ SelectionSetì— ì¡´ì¬í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤.
    # RemoveItems:  ì´ ë©”ì„œë“œëŠ” SelectionSetì—ì„œ í•˜ë‚˜ ì´ìƒì˜ í•­ëª©ì„ ì œê±°í•˜ëŠ” ë° ì‚¬ìš©ë©ë‹ˆë‹¤. ì œê±°ëœ í•­ëª©ì€ ì—¬ì „íˆ â€‹â€‹ì¡´ì¬í•˜ì§€ë§Œ, ë” ì´ìƒ SelectionSetì— ì¡´ì¬í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤.
    # Erase:  ì´ ë©”ì„œë“œëŠ” SelectionSetì˜ ëª¨ë“  í•­ëª©ì„ ì‚­ì œí•©ë‹ˆë‹¤. SelectionSet ê°ì²´ëŠ” ì—¬ì „íˆ ì¡´ì¬í•˜ì§€ë§Œ í•­ëª©ì„ í¬í•¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤. ì´ì „ì— SelectionSetì— ìˆë˜ í•­ëª©ì€ ë” ì´ìƒ ì¡´ì¬í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤.
    # Delete:  SelectionSet ê°ì²´ë¥¼ ì‚­ì œí•˜ì§€ë§Œ, SelectionSetì— í¬í•¨ëœ ê°ì²´ëŠ” ì‚­ì œí•˜ì§€ ì•ŠìŠµë‹ˆë‹¤. Delete ë©”ì„œë“œ í˜¸ì¶œ í›„ SelectionSet ìì²´ëŠ” ë” ì´ìƒ ì¡´ì¬í•˜ì§€ ì•Šì§€ë§Œ, ì´ì „ì— SelectionSetì— í¬í•¨ëœ í•­ëª©ì€ ì—¬ì „íˆ â€‹â€‹ì¡´ì¬í•©ë‹ˆë‹¤.

    # From the methods listed above only RemoveItems method requires parameters to be passed. 
    # For example, from the lines that I have added to SelectionSet I want to remove Line2 (l2). I must pass l2 as an element of the array of the Items list that I want to remove from the SelectionSet.
    ss1.RemoveItems(aVariant([l2]))
    print(ss1.Count)

    # Sometimes I want to select objects using the conventional method only. I.e. dragging/drawing a window around the objects that I want to select using my mouse. Python also allows me to do so using the SelectOnScreen method.
    ss1.SelectOnScreen()
    
    # Once I apply the method as shown above, the code waits for AutoCAD user to select objects. Upon selecting the objects the AutoCAD user needs to press Enter on the keyboard. This will finalize the selection. The code then eventually moves ahead.

    # Group object in AutoCAD using Python
    # The Group object is a named SelectionSet object. Since is does not contain any special methods I have added this small introductory section for the purpose of discussing the Group object.
    # I can add the Group object similarly to how I added the SelectionSet object. I.e. by using the Add method. Obviously, here I need to use the Groups collection object to Add a Group.
    # Also, to add items to the created Group object I can use the AppendItems method. I can perform the task similarly to how I did with the AddItems method for the SelectionSet object.
    # In addition to that here follows a list of various different methods and properties that can be used to perform activities on AutoCAD Group objects:
    # Delete / GetExtensionDictionary / Highlight / Item / RemoveItems / Update / Count / Document / Handle / HasExtensionDictionary / Layer / Linetype / LinetypeScale
    # Lineweight / Material / Name / ObjectID / ObjectName / OwnerID / PlotStyleName / TrueColor / Visible

    # í™”ë©´ ê°±ì‹ 
    acad_app.Update()
    acad_app.ZoomExtents()



if __name__ == "__main__":    
    pythoncom.CoInitialize()  # COM ì´ˆê¸°í™”
    acad = connect_autocad()    
    draw_and_zoom(acad)
    pythoncom.CoUninitialize()