import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding = 'utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding = 'utf-8')

import pythoncom
import time
from pyautocad import Autocad
import win32com.client


def draw_line(x1, y1, x2, y2):
    try:
        # ì‹¤í–‰ ì¤‘ì¸ AutoCAD ì¸ìŠ¤í„´ìŠ¤ì— ì—°ê²°
        acad = win32com.client.GetActiveObject("AutoCAD.Application")
        print("âœ… AutoCAD ì‹¤í–‰ ì¤‘ì…ë‹ˆë‹¤.")
        #return Autocad(create_if_not_exists=False)
    except Exception:
        print("âŒ ì‹¤í–‰ ì¤‘ì¸ AutoCAD ì—†ìŒ. ìƒˆ ì¸ìŠ¤í„´ìŠ¤ë¥¼ ì‹œì‘í•©ë‹ˆë‹¤.")
        try:
            acad = win32com.client.Dispatch("AutoCAD.Application")
            acad.Visible = True
            time.sleep(3)  # ë¡œë”© ëŒ€ê¸°
            print("âœ… ìƒˆ AutoCAD ì¸ìŠ¤í„´ìŠ¤ ì‹œì‘ ì™„ë£Œ.")
            #return Autocad(create_if_not_exists=False)
        except Exception as e:
            print("ğŸš« AutoCAD ì—°ê²° ì‹¤íŒ¨:", e)
            #return None
    #pythoncom.CoInitialize()
    #acad = win32com.client.Dispatch("AutoCAD.Application")
    #acad.Visible = True

    #doc = acad.ActiveDocument
    #ms = doc.ModelSpace
    #ms = acad.ModelSpace

    p1 = win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, (x1, y1, 0))
    p2 = win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, (x2, y2, 0))
    #ms.AddLine(p1, p2)
    line = acad.model.AddLine(p1, p2)

    return 1


if __name__ == "__main__":
    pythoncom.CoInitialize()  # COM ì´ˆê¸°í™”
    #acad = connect_autocad()
    #draw_and_zoom(acad)
    draw_line(0.0, 10.0, 0.0, 10.0)
    pythoncom.CoUninitialize()